Controllers/ContactoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FyJCel.Models;
using FyJCel.Data;

namespace FyJCel.Controllers
{
    public class ContactoController : Controller
    {

        private readonly ApplicationDbContext _context;

        private readonly ILogger<HomeController> _logger;

        public ContactoController(ILogger<HomeController> logger,
            ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        //Descendiente Mayor a Menor
        //Ascendiente Menor a Mayor
        public IActionResult Index()
        {
                                                 //Expresion   
            var listContactos=_context.Contactos.OrderBy(s => s.ID).ToList();
            return View("List",listContactos);

        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public  IActionResult Create(Contacto objContacto){

            if (ModelState.IsValid)
            {
                 objContacto.Mensaje = "Usuario Registrado";

                _context.Add(objContacto);
                _context.SaveChanges();

                 return View(objContacto);   
            }
            return View();
        }

        // GET: http://localhost:5000/Contacto/Edit/6 MUESTRA Contacto
        public IActionResult Edit(int? id)
        {
            if(id == null){
                return NotFound();
            }
            var contacto = _context.Contactos.Find(id);
            if(contacto == null){
                return NotFound();
            }
            return View(contacto);
        }

        //POST: http://localhost:5000/Contacto/Edit/ graba contacto
        [HttpPost]
        public IActionResult Edit(int id, Contacto contacto)
        {
            if (ModelState.IsValid)
            {
                _context.Update(contacto);
                _context.SaveChanges();
            }
            return View(contacto);
        }


        // GET: http://localhost:5000/Contacto/Delete/6 MUESTRA Contacto
        public IActionResult Delete(int? id)
        {
            var contacto = _context.Contactos.Find(id);
            _context.Contactos.Remove(contacto);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FyJCel.Models;
using FyJCel.Data;
//using System.Web;

namespace FyJCel.Controllers
{
    public class ProductoController : Controller
    {

        private readonly ApplicationDbContext _context;

        private readonly ILogger<HomeController> _logger;

        public ProductoController(ILogger<HomeController> logger,
            ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        //Descendiente Mayor a Menor
        //Ascendiente Menor a Mayor
        public IActionResult ListProducto()
        {
                                                 //Expresion   
            var listProductos=_context.productos.OrderBy(s => s.ID).ToList();
            ViewBag.Message="Porfavor, seleccione un producto";
            return View("ListProducto",listProductos);
            
        }

        




        public IActionResult Create()
        {
            return View();
        }



        [HttpPost]
        public ActionResult ProductosSelect(int[] productids)
        {
            List<Producto> productos = new List<Producto>();
            foreach(var i in productids){
                var producto = _context.productos.Find(i);
                productos.Add(producto);
            }
            if(productids.Any()){
                
                ViewBag.Message="Productos agregados";
                return View(productos);
                
            }else{
            
                ViewBag.Message="Seleccione un producto";
                return RedirectToAction("ListProducto");
                
            }
            
        }

        [HttpPost]
        public ActionResult ProductosGrabar(int[] productids, int[] cantidades )
        {
            List<Producto> productos = new List<Producto>();

            for(int i = 0; i<productids.Count(); i++)
            {
                    var objPedido = new Pedido();
                    var objProducto = _context.productos.Find(productids[i]);

                    objPedido.pedi_id_produ = productids[i];
                    objPedido.pedi_cantidad = cantidades[i];
                    objPedido.pedi_precio = objProducto.prod_precio;
            
                    _context.Add(objPedido);
                    _context.SaveChanges();
                    
            }


            //retorno al listado de productos
            var listProductos=_context.productos.OrderBy(s => s.ID).ToList();
            ViewBag.mensajeGrabar = "Los datos se grabaron con éxito - su pedido llegará en una hora a su domicilio";
            return View("ListProducto",listProductos);
            /*return View("ConfirmProducto");*/
        }
        /*[HttpPost]
        public IActionResult ConfirmProducto(String Mens){
            ViewBag.mensajeGrabar = "Los datos se grabaron con éxito - su pedido llegará aprox. en una hora a su domicilio";
            return RedirectToAction("Index");
        }


        public IActionResult ConfirmProducto(){
            
            return View();
        }
        */
       public IActionResult RegProducto()
        {
            return View();
        }

        [HttpPost]
        public  IActionResult RegProducto(Producto objRegProducto){

            if (ModelState.IsValid)
            {
                string[] nombreImagen = objRegProducto.prod_imagen.Split("\\");
        
                objRegProducto.prod_imagen = "/images/" + nombreImagen.Last();

                _context.Add(objRegProducto);
                _context.SaveChanges();

                 ViewBag.mensajeGrabarProducto = "Producto grabado correctamente";
                 ViewBag.Imagen = "/images/" + nombreImagen.Last();
            }
            else
            {
                ViewBag.mensajeGrabarProducto = "Se ha producido un error";
            }
           
            return View();

            //var listProductos=_context.productos.OrderBy(s => s.ID).ToList();
            //return View("ListProducto",listProductos);
            

        }    

/*  inicio comentarios   */
        // GET: http://localhost:5000/Contacto/Edit/6 MUESTRA Contacto
        public IActionResult EditProducto(int? id)
        {
            if(id == null){
                return NotFound();
            }
            var producto = _context.productos.Find(id);
            ViewBag.Imagen = producto.prod_imagen;
            if(producto == null){
                return NotFound();
            }
            return View(producto);
        }

        //POST: http://localhost:5000/Contacto/Edit/ graba contacto
        [HttpPost]
        public IActionResult EditProducto(int id, Producto objRegProducto, string hdnRutaImagen)
        {
            if (ModelState.IsValid)
            {
                string nombreImagen = "";
                string RutaImagen = "";

                if (!string.IsNullOrEmpty(objRegProducto.prod_imagen))
                {
                    string[] nombreImagenSplit = objRegProducto.prod_imagen.Split("\\");
                    nombreImagen = nombreImagenSplit.Last();
                    RutaImagen = "/images/" + nombreImagen; 
                    objRegProducto.prod_imagen = RutaImagen;
                }
                else{
                   //var imagenOriginal = _context.productos.Find(id).prod_imagen;
                   //objRegProducto.prod_imagen = imagenOriginal;
                   //RutaImagen = imagenOriginal;

                   objRegProducto.prod_imagen = hdnRutaImagen;
                   RutaImagen = hdnRutaImagen;
                }
                             
                ViewBag.Imagen = RutaImagen;

                _context.Update(objRegProducto);
                _context.SaveChanges();

                 ViewBag.mensajeGrabarProducto = "Producto grabado correctamente";
                 System.Console.WriteLine(ViewBag.Imagen);
            }
            else
            {
                ViewBag.mensajeGrabarProducto = "Se ha producido un error";
            }
            return View(objRegProducto);
        }


       public IActionResult MantProducto()
        {
            var MantProductos=_context.productos.OrderBy(s => s.ID).ToList();
            return View("MantProducto",MantProductos);
        }

        // GET: http://localhost:5000/Contacto/Delete/6 MUESTRA Contacto
        public IActionResult DelProd(int? id)
        {
            var producto = _context.productos.Find(id);
            _context.productos.Remove(producto);
            _context.SaveChanges();
            return RedirectToAction(nameof(MantProducto));
        }

         public IActionResult Buscar(string texto)
        {
            var textoABuscar = texto.ToUpper();

            var listProductos=_context.productos.Where(x => x.prod_nombre.ToUpper().IndexOf(textoABuscar)>=0);
            
            listProductos = listProductos.OrderBy(s => s.ID);
                  
            return View("ListProducto",listProductos);

        }

        
        
        
    }
}

Controllers/ReclamoController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FyJCel.Models;
using FyJCel.Data;
//using System.Web;

namespace FyJCel.Controllers
{
    public class ReclamoController : Controller
    {

        private readonly ApplicationDbContext _context;

        private readonly ILogger<HomeController> _logger;

        public ReclamoController(ILogger<HomeController> logger,
            ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult CrearReclamo(){
            return View();
        }

        [HttpPost]
        public  IActionResult CrearReclamo(Reclamo objReclamo){

            if (ModelState.IsValid)
            {
                 objReclamo.Mensaje = "Reclamo enviado ... ";

                _context.Add(objReclamo);
                _context.SaveChanges();

                 return View(objReclamo);   
            }
            return View();
        }
    }
}

Views/Shared/_ItemPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Create">Clientes</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark " asp-area="" asp-controller="Contacto" asp-action="Index">Mant. del cliente</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark " asp-area="" asp-controller="Producto" asp-action="RegProducto">Registro Producto</a>
    </li> 
    <li class="nav-item">
        <a class="nav-link text-dark " asp-area="" asp-controller="Producto" asp-action="MantProducto">Mant. Producto</a>
    </li>  
    <li class="nav-item">
        <a class="nav-link text-dark " asp-area="" asp-controller="Producto" asp-action="ListProducto">Delivery</a>
    </li>    
    <li class="nav-item">
        <a class="nav-link text-dark " asp-area="" asp-controller="Reclamo" asp-action="CrearReclamo">Reclamos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark " asp-area="" asp-controller="Pedido" asp-action="Pedido">Estado de Ventas</a>
    </li>

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FyJCel </title>
    
    <link rel="icon" type="image/png" href="https://yt3.ggpht.com/ytc/AAUvwnhBsQCIy7YpYMpeHlvxJgLJReZSqkjEfeVavqWt=s88-c-k-c0x00ffffff-no-rj" /><!--images/icono2.png -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://yt3.ggpht.com/ytc/AAUvwnhBsQCIy7YpYMpeHlvxJgLJReZSqkjEfeVavqWt=s88-c-k-c0x00ffffff-no-rj"  alt="Logo" width="40" height="40"/> FyJCel</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    
                    <ul class="navbar-nav flex-grow-1">
                        
                        
                        <partial name="_ItemPartial" /> 
                         
                    </ul>
                    <partial name="_LoginPartial" />
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FyJCel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>